### ISSUE TITLE
Publish on Github Pages

### ISSUE THREAD

**Issue by profnandaa** [destino92/youtube-homepage#1]
Publish this repo (and others) on Github pages for easy show-casing. It's actually by on click, just go to the repo's _settings_ section and scroll down to:

<img width="772" alt="screen shot 2016-11-28 at 4 08 09 am" src="https://cloud.githubusercontent.com/assets/261265/20653555/57a708fe-b520-11e6-8447-16c5d6711319.png">

Nandaa, from [Kazi+](http://kazi.es).

**Comment by destino92** [comment]
Hello thanks for the heads up will sure do and add a link in README.
